import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import SessionContext from "./SessionContext";
import RQProvider from "./(afterLogin)/_components/RQProvider";
import Script from "next/script";

const notoSansKr = Noto_Sans_KR({
  weight: ["100", "200", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_JS_KEY}&autoload=false&libraries=services`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <RQProvider>
          <SessionContext>
            <div className="h-dvh w-dvw bg-white">
              {children}
              <footer className="flex h-20 items-center justify-center bg-gray-200">
                &copy;2024 All rights reserved by Park Chae Yeon
              </footer>
            </div>
          </SessionContext>
        </RQProvider>
        <Script src={KAKAO_SDK_URL} strategy="beforeInteractive" />
      </body>
    </html>
  );
}
